<?php
/**
 * Created by PhpStorm.
 * User: Cleiton
 * Date: 17/01/2019
 * Time: 16:06
 */

namespace src\entity;
include_once("class/Faturamento.php");

use Faturamento\NotaGUI;
use ExtPDO as PDO;

class ExpedicaoGUI extends NotaGUI implements InterfaceGUI
{
    // ----------------------------------------------------------------------------
    public function __construct($nota = null) {
        $this->nota = is_null($nota) ? null : intval($nota);
        $this->usa_exportacao = false;
        $this->fatura = "S";

        $this->header = array(  "Orçamento", "Nota", "Status", "Pessoa", "Histórico",
                                "Valor", "Emissão", "cód. rastreamento", "cód. transação"
        );
    }

    public function getCampo($linha, $coluna) {
        // indexa o item
        $item = $this->itens[$linha];

        // para a coluna, retorna um array com o valor e a classe a aplicar
        return $this->campos($coluna, array(
            campo($item->handle, "numerico"),
            campo($item->nota_fiscal->numero, "numerico"),
            campo($item->status->nome, "bg-color bg{$item->status->cor}"),
            campo($item->pessoa),
            campo($item->descricao),
            campo(formataValor($item->valor_total), "numerico"),
            campo(converteDataSqlOrdenada($item->data_emissao)),
            campo("<pre>{$item->cod_correios}</pre>"),
            campo("<pre>{$item->cod_pagseguro}</pre>"),
        ));
    }

    public function fetch()
    {
        parent::setPesquisa();
        parent::fetch(); // TODO: Change the autogenerated stub
    }
}